test1

diff --git a/.github/workflows/python-publish.yml b/.github/workflows/python-publish.yml
--- a/.github/workflows/python-publish.yml
+++ b/.github/workflows/python-publish.yml
@@ -70,44 +70,80 @@
 #           packages-dir: dist/
 
 
-name: Robot Framework CI
+# name: Robot Framework CI
 
+# on:
+#   push:
+#     branches:
+#       - master
+#   pull_request:
+#   workflow_dispatch:
+
+# jobs:
+#     Run-Test:
+#       runs-on: ubuntu-20.04
+#       steps:
+#         - name: Checkout repository
+#           uses: actions/checkout@v1
+#         - uses: actions/cache@v2
+#           id: cache
+#           with:
+#             path: ~/.cache/pip
+#             key: ${{ runner.os }}-pip-${{ hashFiles('**/requirement.txt') }}
+#         - name: Install pip dependencies
+#           run: |
+#             pip install --upgrade pip
+#             pip install -r requirements.txt
+#         - name: Run Test
+#           run: python -m robot --outputdir results testSuite/Tim_OP/test_createProject.robot
+#         - name: Run Test and create report
+#           run: python -m robot -d reports -x junit-report.xml "testcases/functional_tests"
+#         - name: Run Robot Framework tests and generate report
+#           run: |
+#              echo "ROBOT_RC=$?" >> "$GITHUB_ENV"  
+#         # - name: If Auto Test Pass Rate Not 100%, Job Will Fail
+#         #   if: env.ROBOT_RC != '0'
+#         #   run: |
+#         #     echo "Auto Test Pass Rate Not 100%, Please Check Test Result"
+#         #     exit 1
+#         - name: Publish test results
+#           uses: actions/upload-artifact@v4
+#           with:
+#             name: robot-test-results
+#             path: results
+
+name: Robot Framework - Python
 on:
   push:
-    branches:
-      - master
+    branches: [ "main" ]
   pull_request:
-  workflow_dispatch:
-
+    branches: [ "main" ]
+ 
+permissions:
+  contents: read
+ 
 jobs:
-    Run-Test:
-      runs-on: ubuntu-20.04
-      steps:
-        - name: Checkout repository
-          uses: actions/checkout@v1
-        - uses: actions/cache@v2
-          id: cache
-          with:
-            path: ~/.cache/pip
-            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirement.txt') }}
-        - name: Install pip dependencies
-          run: |
-            pip install --upgrade pip
-            pip install -r requirements.txt
-        - name: Run Test
-          run: python -m robot --outputdir results testSuite/Tim_OP/test_createProject.robot
-        - name: Run Test and create report
-          run: python -m robot -d reports -x junit-report.xml "testcases/functional_tests"
-        - name: Run Robot Framework tests and generate report
-          run: |
-             echo "ROBOT_RC=$?" >> "$GITHUB_ENV"  
-        # - name: If Auto Test Pass Rate Not 100%, Job Will Fail
-        #   if: env.ROBOT_RC != '0'
-        #   run: |
-        #     echo "Auto Test Pass Rate Not 100%, Please Check Test Result"
-        #     exit 1
-        - name: Publish test results
-          uses: actions/upload-artifact@v4
-          with:
-            name: robot-test-results
-            path: results
+  test:
+    runs-on: ubuntu-latest
+     
+    steps:
+      - uses: actions/checkout@v3
+      - name: Set up Python 3.12.1
+        uses: actions/setup-python@v3
+        with:
+          python-version: 3.12.1
+   
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r requirements.txt
+   
+      - name: Test with RobotFramework
+        run: robot .  
+         
+      - name: Test Report Generation
+        uses: actions/upload-artifact@v4
+        if: success() || failure()
+        with:
+          name: Report                # Name of the folder
+          path: report.html           # Path to test results
